# -*- coding: utf-8 -*-
"""LanguageTranslator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lBGCF72txPZWr6QoR0R8yR0W0YA1VJ7C
"""

!pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

!pip install transformers ipywidgets gradio --upgrade

!pip install sentencepiece

import gradio as gr
from transformers import pipeline
import sentencepiece as spm

classifier=pipeline(model='AbhirupGhosh/opus-mt-finetuned-en-hi')
def translation(text):
  sentences=text.split('\n')
  results=[classifier(sentence)[0]['translation_text']for sentence in sentences if sentence.strip()]
  return '\n'.join(results)

interface_text = gr.Interface(
    fn=translation,
    inputs=gr.inputs.Textbox(lines=10, placeholder='Text to translate'),
    outputs='text',
    label="Translate Text"
)


interface_text.launch()